"""Detect and strip C2PA / AI-related metadata from PNG, JPEG, and WebP (stdlib)."""

from __future__ import annotations

import json
import os
import re
import struct
import subprocess
import sys
import zlib
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from common import classify_finding_confidence, safe_arg, safe_write_bytes, subprocess_preexec_fn, which

SCRIPTS_DIR = Path(__file__).resolve().parent

# CtrlRegen is torch-based and needs far more address space than the stdlib
# parsers. The invoking clean_image.py subprocess applies these higher,
# env-overridable caps instead of the default child limits in common.py.
_CTRLREGEN_RLIMIT_AS = int(os.environ.get("WATERMARKS_CTRLREGEN_RLIMIT_AS", str(32 << 30)))
_CTRLREGEN_RLIMIT_FSIZE = int(os.environ.get("WATERMARKS_CTRLREGEN_RLIMIT_FSIZE", str(2 << 30)))


def ctrlregen_preexec_fn() -> None:
    """Higher resource caps for the CtrlRegen subprocess (torch memory)."""
    try:
        import resource

        resource.setrlimit(resource.RLIMIT_AS, (_CTRLREGEN_RLIMIT_AS, _CTRLREGEN_RLIMIT_AS))
        resource.setrlimit(resource.RLIMIT_FSIZE, (_CTRLREGEN_RLIMIT_FSIZE, _CTRLREGEN_RLIMIT_FSIZE))
    except (ImportError, OSError, ValueError):
        pass


ctrlregen_subprocess_preexec_fn = ctrlregen_preexec_fn if os.name == "posix" else None

PNG_SIG = b"\x89PNG\r\n\x1a\n"
JPEG_SOI = b"\xff\xd8"
WEBP_RIFF = b"RIFF"
WEBP_SIG = b"WEBP"

# Chunk types / content patterns associated with C2PA / AI provenance
C2PA_MARKERS = (
    b"c2pa",
    b"C2PA",
    b"jumb",
    b"JUMB",
    b"c2ma",
    b"contentcredentials",
    b"contentauth",
    b"cai:",
    b"http://ns.adobe.com/xmp/InstanceID/",  # not solely C2PA
)

AI_META_HINTS = (
    b"c2pa",
    b"C2PA",
    b"contentcredentials",
    b"ContentCredentials",
    b"digitalSourceType",
    b"trainedAlgorithmicMedia",
    b"compositeWithTrainedAlgorithmicMedia",
    b"algorithmicMedia",
    b"AIGC",
    b"aigc",
    b"AI generated",
    b"Generated by",
    b"Claude",
    b"Anthropic",
    b"OpenAI",
    b"SynthID",
    b"dcterms:provenance",
)


@dataclass
class ImageInspectReport:
    path: str
    format: str  # png | jpeg | webp | unknown
    has_c2pa: bool
    has_ai_metadata: bool
    findings: list[str] = field(default_factory=list)
    tools: dict[str, Any] = field(default_factory=dict)
    synthid: dict[str, Any] | None = None
    notes: list[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "path": self.path,
            "format": self.format,
            "has_c2pa": self.has_c2pa,
            "has_ai_metadata": self.has_ai_metadata,
            "findings": self.findings,
            "findings_confidence": [
                classify_finding_confidence(f) for f in self.findings
            ],
            "tools": self.tools,
            "synthid": self.synthid,
            "notes": self.notes,
        }


def detect_format(data: bytes) -> str:
    if data.startswith(PNG_SIG):
        return "png"
    if data.startswith(JPEG_SOI):
        return "jpeg"
    if len(data) >= 12 and data[:4] == WEBP_RIFF and data[8:12] == WEBP_SIG:
        return "webp"
    if len(data) >= 12 and data[4:8] == b"ftyp":
        box_size = struct.unpack(">I", data[0:4])[0]
        header_chunk = (
            data[8:min(box_size, len(data), 64)]
            if box_size >= 8
            else data[8:min(len(data), 64)]
        )
        if any(b in header_chunk for b in (b"avif", b"avis", b"avio")):
            return "avif"
        if any(
            b in header_chunk
            for b in (b"heic", b"heix", b"hevc", b"heim", b"heis", b"mif1", b"msf1", b"heif")
        ):
            return "heic"
    return "unknown"


def _contains_any(blob: bytes, needles: tuple[bytes, ...]) -> list[str]:
    found = []
    lower = blob.lower()
    for n in needles:
        if n.lower() in lower:
            try:
                found.append(n.decode("ascii", errors="replace"))
            except Exception:
                found.append(repr(n))
    return found


def inspect_png(data: bytes) -> tuple[bool, bool, list[str]]:
    findings: list[str] = []
    has_c2pa = False
    has_ai = False
    if not data.startswith(PNG_SIG):
        return False, False, ["not a PNG"]
    pos = 8
    while pos + 8 <= len(data):
        length = struct.unpack(">I", data[pos : pos + 4])[0]
        ctype = data[pos + 4 : pos + 8]
        chunk_start = pos + 8
        chunk_end = chunk_start + length
        if chunk_end + 4 > len(data):
            findings.append(f"truncated chunk {ctype!r}")
            break
        payload = data[chunk_start:chunk_end]
        name = ctype.decode("latin-1", errors="replace")
        # Private/ancillary chunks sometimes used for JUMBF/C2PA
        if ctype in (b"caBX", b"juMB", b"jumb") or ctype.startswith(b"c2"):
            has_c2pa = True
            findings.append(f"PNG chunk {name} (possible C2PA container)")
        if ctype in (b"tEXt", b"zTXt", b"iTXt", b"eXIf"):
            hits = _contains_any(payload, AI_META_HINTS + C2PA_MARKERS)
            if hits:
                has_ai = True
                if any(h.lower() in ("c2pa", "contentcredentials", "jumb") for h in hits):
                    has_c2pa = True
                findings.append(f"PNG {name}: {', '.join(hits[:8])}")
        if ctype == b"IEND":
            break
        pos = chunk_end + 4  # skip CRC
    # Whole-file scan fallback
    whole = _contains_any(data, C2PA_MARKERS)
    if whole and not has_c2pa:
        has_c2pa = True
        findings.append(f"byte-scan C2PA markers: {', '.join(whole[:6])}")
    return has_c2pa, has_ai or has_c2pa, findings


def inspect_jpeg(data: bytes) -> tuple[bool, bool, list[str]]:
    findings: list[str] = []
    has_c2pa = False
    has_ai = False
    if not data.startswith(JPEG_SOI):
        return False, False, ["not a JPEG"]
    i = 2
    n = len(data)
    while i + 4 <= n:
        if data[i] != 0xFF:
            i += 1
            continue
        # skip fill
        while i < n and data[i] == 0xFF:
            i += 1
        if i >= n:
            break
        marker = data[i]
        i += 1
        if marker in (0xD8, 0xD9):  # SOI/EOI
            continue
        if marker == 0xDA:  # SOS — image data follows
            break
        if marker >= 0xD0 and marker <= 0xD7:  # RSTn
            continue
        if i + 2 > n:
            break
        seglen = struct.unpack(">H", data[i : i + 2])[0]
        if seglen < 2 or i + seglen > n:
            findings.append(f"bad segment length at marker 0x{marker:02X}")
            break
        payload = data[i + 2 : i + seglen]
        i += seglen

        # APP11 (0xEB) often holds JUMBF/C2PA
        if marker == 0xEB:
            has_c2pa = True
            findings.append("JPEG APP11 segment (JUMBF/C2PA common)")
        if marker in (0xE1, 0xE2, 0xED, 0xEE, 0xEB):  # APP1,2,13,14,11
            hits = _contains_any(payload, AI_META_HINTS + C2PA_MARKERS)
            if hits:
                has_ai = True
                if any(
                    h.lower() in ("c2pa", "contentcredentials", "jumb", "contentauth")
                    for h in hits
                ):
                    has_c2pa = True
                findings.append(f"JPEG APP{marker - 0xE0}: {', '.join(hits[:8])}")

    whole = _contains_any(data, C2PA_MARKERS)
    if whole and not has_c2pa:
        has_c2pa = True
        findings.append(f"byte-scan C2PA markers: {', '.join(whole[:6])}")
    return has_c2pa, has_ai or has_c2pa, findings


def _webp_chunks(data: bytes) -> tuple[list[tuple[bytes, bytes, bytes]], list[str]]:
    if detect_format(data) != "webp":
        return [], ["not a WebP"]

    notes: list[str] = []
    declared_size = struct.unpack("<I", data[4:8])[0]
    if declared_size + 8 != len(data):
        notes.append(
            f"RIFF size mismatch: header={declared_size + 8} actual={len(data)}"
        )

    chunks: list[tuple[bytes, bytes, bytes]] = []
    pos = 12
    while pos + 8 <= len(data):
        fourcc = data[pos : pos + 4]
        length = struct.unpack("<I", data[pos + 4 : pos + 8])[0]
        payload_start = pos + 8
        payload_end = payload_start + length
        padded_end = payload_end + (length & 1)
        if padded_end > len(data):
            name = fourcc.decode("latin-1", errors="replace")
            notes.append(f"truncated WebP chunk {name}")
            break
        chunks.append(
            (fourcc, data[payload_start:payload_end], data[payload_end:padded_end])
        )
        pos = padded_end
    if pos != len(data) and not any("truncated" in note for note in notes):
        notes.append(f"trailing WebP bytes: {len(data) - pos}")
    return chunks, notes


def inspect_webp(data: bytes) -> tuple[bool, bool, list[str]]:
    chunks, findings = _webp_chunks(data)
    if not chunks and findings == ["not a WebP"]:
        return False, False, findings

    has_c2pa = False
    has_ai = False
    for fourcc, payload, _padding in chunks:
        name = fourcc.decode("latin-1", errors="replace")
        if fourcc.upper() == b"C2PA":
            has_c2pa = True
            has_ai = True
            findings.append("WebP C2PA chunk")
            continue
        if fourcc in (b"XMP ", b"EXIF"):
            hits = _contains_any(payload, AI_META_HINTS + C2PA_MARKERS)
            if hits:
                has_ai = True
                if any(
                    hit.lower() in ("c2pa", "contentcredentials", "jumb", "contentauth")
                    for hit in hits
                ):
                    has_c2pa = True
                findings.append(f"WebP {name}: {', '.join(hits[:8])}")
    return has_c2pa, has_ai or has_c2pa, findings


XMP_UUID = b"\xbe\x7a\xcf\xcb\x97\xa9\x42\xe8\x9c\x71\x99\x94\x91\xe3\xaf\xac"


def _parse_isobmff_boxes(
    data: bytes, start: int = 0, end: int | None = None
) -> list[tuple[bytes, bytes, int, int]]:
    """Parse top-level or container ISOBMFF boxes.

    Returns list of (fourcc, payload, total_box_size, header_size).
    """
    if end is None:
        end = len(data)
    boxes = []
    pos = start
    while pos + 8 <= end:
        size = struct.unpack(">I", data[pos : pos + 4])[0]
        fourcc = data[pos + 4 : pos + 8]
        header_size = 8
        if size == 1:
            if pos + 16 > end:
                break
            size = struct.unpack(">Q", data[pos + 8 : pos + 16])[0]
            header_size = 16
        elif size == 0:
            size = end - pos

        if size < header_size or pos + size > end:
            break
        payload = data[pos + header_size : pos + size]
        boxes.append((fourcc, payload, size, header_size))
        pos += size
    return boxes


def inspect_isobmff(data: bytes, fmt: str = "avif") -> tuple[bool, bool, list[str]]:
    findings: list[str] = []
    has_c2pa = False
    has_ai = False

    boxes = _parse_isobmff_boxes(data)
    if not boxes:
        return False, False, [f"not a valid {fmt.upper()} (no ISOBMFF boxes found)"]

    for fourcc, payload, _, _ in boxes:
        name = fourcc.decode("latin-1", errors="replace")
        if fourcc in (b"jumb", b"c2pa") or name.lower().startswith("c2"):
            has_c2pa = True
            findings.append(f"{fmt.upper()} top-level box {name} (C2PA/JUMBF manifest)")
        elif fourcc == b"uuid":
            if payload.startswith(XMP_UUID):
                has_ai = True
                xmp_text = payload[16:]
                hits = _contains_any(xmp_text, AI_META_HINTS + C2PA_MARKERS)
                if hits:
                    findings.append(f"{fmt.upper()} XMP uuid box: {', '.join(hits[:8])}")
                else:
                    findings.append(f"{fmt.upper()} XMP uuid box")
                if any(
                    h.lower() in ("c2pa", "contentcredentials", "jumb", "contentauth")
                    for h in hits
                ):
                    has_c2pa = True
            else:
                hits = _contains_any(payload, AI_META_HINTS + C2PA_MARKERS)
                if hits:
                    has_ai = True
                    findings.append(f"{fmt.upper()} uuid box: {', '.join(hits[:8])}")
                    if any(
                        h.lower() in ("c2pa", "contentcredentials", "jumb")
                        for h in hits
                    ):
                        has_c2pa = True
        elif fourcc == b"meta":
            meta_sub = _parse_isobmff_boxes(payload, start=4)
            for s_fourcc, s_payload, _, _ in meta_sub:
                s_name = s_fourcc.decode("latin-1", errors="replace")
                if s_fourcc in (b"jumb", b"c2pa") or s_name.lower().startswith("c2"):
                    has_c2pa = True
                    findings.append(
                        f"{fmt.upper()} meta sub-box {s_name} (C2PA/JUMBF container)"
                    )
                elif s_fourcc == b"uuid":
                    if s_payload.startswith(XMP_UUID):
                        has_ai = True
                        hits = _contains_any(
                            s_payload[16:], AI_META_HINTS + C2PA_MARKERS
                        )
                        if hits:
                            findings.append(
                                f"{fmt.upper()} meta XMP uuid: {', '.join(hits[:8])}"
                            )
                        else:
                            findings.append(f"{fmt.upper()} meta XMP uuid box")
                        if any(
                            h.lower() in ("c2pa", "contentcredentials", "jumb")
                            for h in hits
                        ):
                            has_c2pa = True
                    else:
                        hits = _contains_any(s_payload, AI_META_HINTS + C2PA_MARKERS)
                        if hits:
                            has_ai = True
                            findings.append(f"{fmt.upper()} meta uuid: {', '.join(hits[:8])}")
                elif s_fourcc in (b"iinf", b"infe", b"iref", b"iloc", b"xml ", b"bxml"):
                    hits = _contains_any(s_payload, AI_META_HINTS + C2PA_MARKERS)
                    if hits:
                        has_ai = True
                        if any(
                            h.lower() in ("c2pa", "contentcredentials", "jumb")
                            for h in hits
                        ):
                            has_c2pa = True
                        findings.append(
                            f"{fmt.upper()} meta/{s_name}: {', '.join(hits[:8])}"
                        )

    whole = _contains_any(data, C2PA_MARKERS)
    if whole and not has_c2pa:
        has_c2pa = True
        findings.append(f"byte-scan C2PA markers: {', '.join(whole[:6])}")

    return has_c2pa, has_ai or has_c2pa, findings


def run_optional_tools(path: Path) -> dict[str, Any]:
    tools: dict[str, Any] = {}
    c2patool = which("c2patool")
    if c2patool:
        try:
            r = subprocess.run(
                [c2patool, safe_arg(str(path))],
                capture_output=True,
                text=True,
                timeout=30,
                preexec_fn=subprocess_preexec_fn,
            )
            out = (r.stdout or "") + (r.stderr or "")
            low = out.lower()
            # Negative markers must veto every positive branch, so the
            # positive alternatives are parenthesised: c2patool reports a
            # missing manifest as "Error: No claim found", which contains
            # the substring "claim" and would otherwise read as a hit.
            no_manifest = "no claim" in low or "no jumbf" in low
            tools["c2patool"] = {
                "available": True,
                "returncode": r.returncode,
                "snippet": out[:2000],
                "has_manifest": (
                    "claim" in low or "c2pa" in low or "manifest" in low
                )
                and not no_manifest,
            }
        except Exception as e:
            tools["c2patool"] = {"available": True, "error": str(e)}
    else:
        tools["c2patool"] = {"available": False}

    exiftool = which("exiftool")
    if exiftool:
        try:
            r = subprocess.run(
                [exiftool, "-G1", "-a", "-s", safe_arg(str(path))],
                capture_output=True,
                text=True,
                timeout=30,
                preexec_fn=subprocess_preexec_fn,
            )
            out = r.stdout or ""
            interesting = [
                line
                for line in out.splitlines()
                if re.search(
                    r"c2pa|content.?credential|AIGC|digitalSource|XMP|EXIF|IPTC|jumb",
                    line,
                    re.I,
                )
            ]
            tools["exiftool"] = {
                "available": True,
                "interesting_lines": interesting[:50],
            }
        except Exception as e:
            tools["exiftool"] = {"available": True, "error": str(e)}
    else:
        tools["exiftool"] = {"available": False}
    return tools


def run_synthid_score(
    path: Path,
    upstream_dir: str | None = None,
) -> dict[str, Any] | None:
    """Run the optional reverse-SynthID scorer in a subprocess.

    Returns None when the scorer is not configured or unavailable (exit 3),
    so callers can keep the default "no SynthID score" behavior.
    """
    if upstream_dir is None:
        upstream_dir = os.environ.get("REVERSE_SYNTHID_DIR")
    if not upstream_dir:
        return None

    script = SCRIPTS_DIR / "score_synthid.py"
    cmd = [
        sys.executable,
        str(script),
        str(path),
        "--upstream-dir",
        str(upstream_dir),
        "--json",
    ]
    try:
        r = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=180,
            preexec_fn=subprocess_preexec_fn,
        )
    except Exception as e:
        return {"available": False, "error": str(e)}

    if r.returncode == 3:
        return None
    if r.returncode != 0:
        return {"available": False, "error": (r.stderr or "").strip()[:2000]}
    try:
        return json.loads(r.stdout or "{}")
    except json.JSONDecodeError as e:
        return {"available": False, "error": f"bad scorer JSON: {e}"}


def _ctrlregen_python(upstream: Path) -> str:
    """Prefer the checkout venv so torch/diffusers are importable."""
    if os.name == "nt":
        venv = upstream / ".venv" / "Scripts" / "python.exe"
    else:
        venv = upstream / ".venv" / "bin" / "python"
    if venv.is_file():
        return str(venv)
    return sys.executable


def _markdiffusion_python(upstream: Path | None) -> str:
    """Prefer the bootstrap venv so torch/diffusers/markdiffusion importable."""
    if upstream is not None:
        if os.name == "nt":
            venv = upstream / ".venv" / "Scripts" / "python.exe"
        else:
            venv = upstream / ".venv" / "bin" / "python"
        if venv.is_file():
            return str(venv)
    return sys.executable


def run_markdiffusion_purify(
    path: Path,
    output: Path,
    *,
    upstream_dir: str | None = None,
    strength: float = 0.3,
    model: str | None = None,
    size: int = 512,
    steps: int = 50,
    device: str | None = None,
    timeout: int = 3600,
) -> dict[str, Any]:
    """Run the optional MarkDiffusion DiffusionPurification remover in a subprocess.

    Returns ``{"available": False, "error": ...}`` when the backend is not
    configured, its dependencies are missing, or it fails at runtime; a
    successful run is ``{"available": True, ...}``.
    """
    if upstream_dir is None:
        upstream_dir = os.environ.get("MARKDIFFUSION_DIR")

    upstream = (
        Path(upstream_dir).expanduser().resolve() if upstream_dir else None
    )
    if upstream is not None and not upstream.is_dir():
        return {
            "available": False,
            "error": f"MarkDiffusion dir not found: {upstream}",
        }

    script = SCRIPTS_DIR / "markdiffusion_harness.py"
    cmd = [
        _markdiffusion_python(upstream),
        str(script),
        "purify",
        str(path),
        "-o",
        str(output),
        "--purification-strength",
        str(strength),
        "--size",
        str(size),
        "--steps",
        str(steps),
        "--json",
    ]
    if upstream is not None:
        cmd += ["--upstream-dir", str(upstream)]
    if model:
        cmd += ["--model", str(model)]
    if device:
        cmd += ["--device", str(device)]

    try:
        r = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=timeout,
            preexec_fn=ctrlregen_subprocess_preexec_fn,
        )
    except subprocess.TimeoutExpired:
        return {
            "available": False,
            "error": f"DiffusionPurification timed out after {timeout}s",
        }
    except Exception as e:
        return {"available": False, "error": str(e)}

    if r.returncode != 0:
        return {"available": False, "error": (r.stderr or "").strip()[:2000]}
    try:
        payload = json.loads(r.stdout or "{}")
    except json.JSONDecodeError as e:
        return {
            "available": False,
            "error": f"bad MarkDiffusion adapter JSON: {e}",
        }
    payload["available"] = True
    return payload


def run_ctrlregen_clean(
    path: Path,
    output: Path,
    *,
    upstream_dir: str | None = None,
    strength: float = 0.25,
    steps: int = 50,
    device: str | None = None,
    seed: int | None = None,
    timeout: int = 3600,
) -> dict[str, Any]:
    """Run the optional CtrlRegen remover in a subprocess.

    Returns ``{"available": False, "error": ...}`` when the remover is not
    configured, its dependencies are missing, or it fails at runtime; a
    successful run is ``{"available": True, ...}``.
    """
    if upstream_dir is None:
        upstream_dir = os.environ.get("NOAI_WATERMARK_DIR")
    if not upstream_dir:
        return {
            "available": False,
            "error": "CtrlRegen not configured (set NOAI_WATERMARK_DIR or pass --ctrlregen-dir)",
        }

    upstream = Path(upstream_dir).expanduser().resolve()
    if not upstream.is_dir():
        return {"available": False, "error": f"CtrlRegen dir not found: {upstream}"}

    script = SCRIPTS_DIR / "clean_ctrlregen.py"
    cmd = [
        _ctrlregen_python(upstream),
        str(script),
        str(path),
        "-o",
        str(output),
        "--upstream-dir",
        str(upstream),
        "--strength",
        str(strength),
        "--steps",
        str(steps),
        "--json",
    ]
    if device:
        cmd += ["--device", str(device)]
    if seed is not None:
        cmd += ["--seed", str(seed)]

    try:
        r = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=timeout,
            preexec_fn=ctrlregen_subprocess_preexec_fn,
        )
    except subprocess.TimeoutExpired:
        return {"available": False, "error": f"CtrlRegen timed out after {timeout}s"}
    except Exception as e:
        return {"available": False, "error": str(e)}

    if r.returncode != 0:
        return {"available": False, "error": (r.stderr or "").strip()[:2000]}
    try:
        payload = json.loads(r.stdout or "{}")
    except json.JSONDecodeError as e:
        return {"available": False, "error": f"bad CtrlRegen adapter JSON: {e}"}
    payload["available"] = True
    return payload


def inspect_image(
    path: Path,
    synthid_dir: str | None = None,
) -> ImageInspectReport:
    data = path.read_bytes()
    fmt = detect_format(data)
    if fmt == "png":
        has_c2pa, has_ai, findings = inspect_png(data)
    elif fmt == "jpeg":
        has_c2pa, has_ai, findings = inspect_jpeg(data)
    elif fmt == "webp":
        has_c2pa, has_ai, findings = inspect_webp(data)
    elif fmt in ("avif", "heic"):
        has_c2pa, has_ai, findings = inspect_isobmff(data, fmt)
    else:
        has_c2pa, has_ai, findings = False, False, [
            "unsupported format (PNG/JPEG/WebP/AVIF/HEIC)"
        ]

    notes: list[str] = []
    if fmt == "unknown":
        notes.append("format not fully inspected; only PNG/JPEG/WebP/AVIF/HEIC are supported")

    tools = run_optional_tools(path)
    # Elevate flags from tools
    ct = tools.get("c2patool") or {}
    if ct.get("has_manifest"):
        has_c2pa = True
        findings.append("c2patool reports a C2PA-related manifest")

    return ImageInspectReport(
        path=str(path),
        format=fmt,
        has_c2pa=has_c2pa,
        has_ai_metadata=has_ai,
        findings=findings,
        tools=tools,
        synthid=run_synthid_score(path, synthid_dir),
        notes=notes,
    )


def _png_chunk(ctype: bytes, payload: bytes) -> bytes:
    crc = zlib.crc32(ctype)
    crc = zlib.crc32(payload, crc) & 0xFFFFFFFF
    return struct.pack(">I", len(payload)) + ctype + payload + struct.pack(">I", crc)


def strip_png(data: bytes, *, strip_all_text: bool = True) -> tuple[bytes, list[str]]:
    if not data.startswith(PNG_SIG):
        raise ValueError("not PNG")
    actions: list[str] = []
    out = bytearray(PNG_SIG)
    pos = 8
    while pos + 8 <= len(data):
        length = struct.unpack(">I", data[pos : pos + 4])[0]
        ctype = data[pos + 4 : pos + 8]
        chunk_start = pos + 8
        chunk_end = chunk_start + length
        if chunk_end + 4 > len(data):
            break
        payload = data[chunk_start:chunk_end]
        crc_bytes = data[chunk_end : chunk_end + 4]
        pos = chunk_end + 4
        name = ctype.decode("latin-1", errors="replace")

        drop = False
        if ctype in (b"eXIf", b"caBX") or ctype.startswith(b"c2"):
            drop = True
            actions.append(f"drop chunk {name}")
        elif ctype in (b"tEXt", b"zTXt", b"iTXt"):
            if strip_all_text or _contains_any(payload, AI_META_HINTS + C2PA_MARKERS):
                drop = True
                actions.append(f"drop chunk {name}")
        elif _contains_any(ctype + payload, C2PA_MARKERS) and ctype not in (
            b"IHDR",
            b"IDAT",
            b"IEND",
            b"PLTE",
            b"tRNS",
            b"gAMA",
            b"pHYs",
            b"sRGB",
            b"cHRM",
            b"iCCP",
        ):
            drop = True
            actions.append(f"drop chunk {name} (C2PA marker in payload)")

        if not drop:
            out.extend(struct.pack(">I", length) + ctype + payload + crc_bytes)
        if ctype == b"IEND":
            break
    if not actions:
        actions.append("no PNG metadata chunks removed (already clean or none matched)")
    return bytes(out), actions


def strip_jpeg(data: bytes, *, strip_all_app: bool = True) -> tuple[bytes, list[str]]:
    if not data.startswith(JPEG_SOI):
        raise ValueError("not JPEG")
    actions: list[str] = []
    out = bytearray(JPEG_SOI)
    i = 2
    n = len(data)
    while i < n:
        if data[i] != 0xFF:
            # unexpected; copy rest
            out.extend(data[i:])
            actions.append("copied remainder after non-marker byte")
            break
        while i < n and data[i] == 0xFF:
            i += 1
        if i >= n:
            break
        marker = data[i]
        i += 1

        if marker == 0xD9:  # EOI
            out.extend(b"\xff\xd9")
            break
        if marker == 0xD8:  # nested SOI?
            continue
        if 0xD0 <= marker <= 0xD7:
            out.extend(bytes([0xFF, marker]))
            continue
        if marker == 0xDA:  # SOS — copy through end
            # need length of SOS header then entropy-coded data to EOI
            if i + 2 > n:
                break
            seglen = struct.unpack(">H", data[i : i + 2])[0]
            # Find EOI from here carefully: after SOS segment header, scan for FF D9
            # not preceded by stuffed FF 00 issues — simple approach: copy from FF DA to end
            sos_start = i - 2  # points at 0xFF before marker... actually marker already consumed
            # Reconstruct: FF DA + rest of file
            out.extend(b"\xff\xda")
            out.extend(data[i:])
            actions.append("preserved entropy-coded scan (SOS→EOF)")
            break

        if i + 2 > n:
            break
        seglen = struct.unpack(">H", data[i : i + 2])[0]
        if seglen < 2 or i + seglen > n:
            out.extend(data[i - 2 :])  # best effort
            actions.append("truncated segment; copied remainder")
            break
        payload = data[i + 2 : i + seglen]
        next_i = i + seglen

        # APP0 is JFIF — keep for compatibility unless full strip of all APP
        keep = False
        drop = False
        if 0xE0 <= marker <= 0xEF:  # APPn
            if marker == 0xEB:  # APP11 JUMBF/C2PA
                drop = True
                actions.append("drop APP11 (C2PA/JUMBF)")
            elif strip_all_app and marker != 0xE0:
                # keep APP0 (JFIF) by default
                drop = True
                actions.append(f"drop APP{marker - 0xE0}")
            elif _contains_any(payload, AI_META_HINTS + C2PA_MARKERS):
                drop = True
                actions.append(f"drop APP{marker - 0xE0} (AI/C2PA markers)")
            else:
                keep = True
        elif marker in (0xFE,):  # COM
            drop = True
            actions.append("drop COM comment")
        else:
            keep = True

        if keep and not drop:
            out.extend(bytes([0xFF, marker]))
            out.extend(data[i : i + seglen])
        i = next_i

    if not actions:
        actions.append("no JPEG APP segments removed")
    return bytes(out), actions


def strip_webp(data: bytes, *, strip_all_metadata: bool = True) -> tuple[bytes, list[str]]:
    chunks, notes = _webp_chunks(data)
    if not chunks and notes == ["not a WebP"]:
        raise ValueError("not WebP")
    if notes:
        raise ValueError("malformed WebP: " + "; ".join(notes))

    actions: list[str] = []
    kept: list[tuple[bytes, bytes, bytes]] = []
    removed_flags = 0
    metadata_flags = {b"ICCP": 0x20, b"EXIF": 0x08, b"XMP ": 0x04}

    for fourcc, payload, padding in chunks:
        drop = fourcc.upper() == b"C2PA"
        if fourcc in metadata_flags:
            drop = strip_all_metadata or bool(
                _contains_any(payload, AI_META_HINTS + C2PA_MARKERS)
            )
        if drop:
            name = fourcc.decode("latin-1", errors="replace")
            actions.append(f"drop WebP chunk {name}")
            removed_flags |= metadata_flags.get(fourcc, 0)
        else:
            kept.append((fourcc, payload, padding))

    body = bytearray(WEBP_SIG)
    for fourcc, payload, padding in kept:
        if fourcc == b"VP8X" and len(payload) >= 1 and removed_flags:
            payload = bytes([payload[0] & ~removed_flags]) + payload[1:]
        body.extend(fourcc)
        body.extend(struct.pack("<I", len(payload)))
        body.extend(payload)
        body.extend(padding if len(payload) & 1 else b"")

    if not actions:
        actions.append("no WebP metadata chunks removed (already clean or none matched)")
    return WEBP_RIFF + struct.pack("<I", len(body)) + bytes(body), actions


def strip_isobmff(
    data: bytes, fmt: str = "avif", *, strip_all_metadata: bool = True
) -> tuple[bytes, list[str]]:
    boxes = _parse_isobmff_boxes(data)
    if not boxes:
        raise ValueError(f"not a valid {fmt.upper()} (no ISOBMFF boxes)")

    actions: list[str] = []
    out = bytearray()

    for fourcc, payload, size, header_size in boxes:
        name = fourcc.decode("latin-1", errors="replace")
        if fourcc in (b"jumb", b"c2pa") or name.lower().startswith("c2"):
            actions.append(f"drop top-level {name} box (C2PA/JUMBF)")
            continue

        if fourcc == b"uuid":
            if payload.startswith(XMP_UUID):
                actions.append(f"drop top-level {name} box (XMP metadata)")
                continue
            if strip_all_metadata or _contains_any(payload, AI_META_HINTS + C2PA_MARKERS):
                actions.append(f"drop top-level {name} box (UUID metadata)")
                continue

        if fourcc == b"meta":
            meta_verflags = payload[:4] if len(payload) >= 4 else b"\x00\x00\x00\x00"
            sub_boxes = _parse_isobmff_boxes(payload, start=4)
            clean_sub = bytearray()
            for s_fourcc, s_payload, s_size, s_hdr in sub_boxes:
                s_name = s_fourcc.decode("latin-1", errors="replace")
                if s_fourcc in (b"jumb", b"c2pa") or s_name.lower().startswith("c2"):
                    actions.append(f"drop meta sub-box {s_name} (C2PA/JUMBF)")
                    continue
                if s_fourcc == b"uuid":
                    if s_payload.startswith(XMP_UUID):
                        actions.append(f"drop meta sub-box {s_name} (XMP metadata)")
                        continue
                    if strip_all_metadata or _contains_any(
                        s_payload, AI_META_HINTS + C2PA_MARKERS
                    ):
                        actions.append(f"drop meta sub-box {s_name} (UUID metadata)")
                        continue
                if s_fourcc in (b"xml ", b"bxml"):
                    if strip_all_metadata or _contains_any(
                        s_payload, AI_META_HINTS + C2PA_MARKERS
                    ):
                        actions.append(f"drop meta sub-box {s_name} (XML metadata)")
                        continue
                clean_sub.extend(
                    struct.pack(">I", len(s_payload) + 8) + s_fourcc + s_payload
                )

            new_meta_payload = meta_verflags + clean_sub
            out.extend(
                struct.pack(">I", len(new_meta_payload) + 8) + b"meta" + new_meta_payload
            )
            continue

        out.extend(struct.pack(">I", len(payload) + 8) + fourcc + payload)

    if not actions:
        actions.append(
            f"no {fmt.upper()} metadata boxes removed (already clean or none matched)"
        )

    return bytes(out), actions


def clean_image(
    path: Path,
    dest: Path,
    *,
    strip_all_metadata: bool = True,
    synthid_dir: str | None = None,
    remove_pixel: str | None = None,
    ctrlregen_dir: str | None = None,
    ctrlregen_strength: float = 0.25,
    ctrlregen_steps: int = 50,
    ctrlregen_device: str | None = None,
    ctrlregen_seed: int | None = None,
    ctrlregen_timeout: int = 3600,
    markdiffusion_dir: str | None = None,
    markdiffusion_strength: float = 0.3,
    markdiffusion_model: str | None = None,
    markdiffusion_size: int = 512,
    markdiffusion_steps: int = 50,
    markdiffusion_device: str | None = None,
    markdiffusion_timeout: int = 3600,
) -> dict[str, Any]:
    synthid_before = run_synthid_score(path, synthid_dir)
    data = path.read_bytes()
    fmt = detect_format(data)
    if fmt == "png":
        cleaned, actions = strip_png(data, strip_all_text=strip_all_metadata)
    elif fmt == "jpeg":
        cleaned, actions = strip_jpeg(data, strip_all_app=strip_all_metadata)
    elif fmt == "webp":
        cleaned, actions = strip_webp(data, strip_all_metadata=strip_all_metadata)
    elif fmt in ("avif", "heic"):
        cleaned, actions = strip_isobmff(data, fmt, strip_all_metadata=strip_all_metadata)
    else:
        raise ValueError(f"unsupported format: {fmt}")

    # Optional exiftool pass for residual tags
    safe_write_bytes(dest, cleaned)
    exiftool = which("exiftool")
    if exiftool and strip_all_metadata:
        try:
            subprocess.run(
                [
                    exiftool,
                    "-all=",
                    "-overwrite_original",
                    safe_arg(str(dest)),
                ],
                capture_output=True,
                text=True,
                timeout=60,
                check=False,
                preexec_fn=subprocess_preexec_fn,
            )
            actions.append("exiftool -all= pass")
        except Exception as e:
            actions.append(f"exiftool failed: {e}")

    pixel_removal: dict[str, Any] | None = None
    if remove_pixel:
        if remove_pixel == "ctrlregen":
            pixel_removal = run_ctrlregen_clean(
                dest,
                dest,
                upstream_dir=ctrlregen_dir,
                strength=ctrlregen_strength,
                steps=ctrlregen_steps,
                device=ctrlregen_device,
                seed=ctrlregen_seed,
                timeout=ctrlregen_timeout,
            )
            if pixel_removal.get("available"):
                actions.append(f"CtrlRegen pixel removal (strength {ctrlregen_strength})")
            else:
                actions.append(
                    "CtrlRegen pixel removal skipped: "
                    f"{pixel_removal.get('error', 'unknown error')}"
                )
        elif remove_pixel == "diffusion":
            pixel_removal = run_markdiffusion_purify(
                dest,
                dest,
                upstream_dir=markdiffusion_dir,
                strength=markdiffusion_strength,
                model=markdiffusion_model,
                size=markdiffusion_size,
                steps=markdiffusion_steps,
                device=markdiffusion_device,
                timeout=markdiffusion_timeout,
            )
            if pixel_removal.get("available"):
                actions.append(
                    f"DiffusionPurification pixel removal "
                    f"(strength {markdiffusion_strength})"
                )
            else:
                actions.append(
                    "DiffusionPurification pixel removal skipped: "
                    f"{pixel_removal.get('error', 'unknown error')}"
                )
        else:
            raise ValueError(f"unknown pixel remover: {remove_pixel}")

    after = inspect_image(dest, synthid_dir=synthid_dir)
    return {
        "input": str(path),
        "output": str(dest),
        "format": fmt,
        "actions": actions,
        "bytes_in": len(data),
        "bytes_out": dest.stat().st_size,
        "still_has_c2pa": after.has_c2pa,
        "still_has_ai_metadata": after.has_ai_metadata,
        "post_findings": after.findings,
        "synthid_before": synthid_before,
        "synthid_after": after.synthid,
        "pixel_removal": pixel_removal,
    }
